
server:
  port: 8989
  servlet:
    context-path: /huang-li
#?????????????
spring:
  mvc:
    view:
      prefix: /  # /???????webapp???
      suffix: .jsp
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/hli?serverTimezone=Asia/Shanghai&useTimezone=true
    # ?????
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
  typeAliasesPackage: com.yuzun.demo.entity
